package main

// DO NOT MODIFY: generated by github.com/ttacon/toml2cli
// If you need to make changes, update the toml config and then regenerate
// this file.

import (
	"log"
	"os"

	cli "github.com/urfave/cli/v2"
)

func main() {
	app := cli.NewApp()
	app.Name = "ope"
	app.Usage = "1password events exploration CLI"

	app.Commands = []*cli.Command{
		{
			Name:        "introspect",
			Description: "Introspect the provided token",
			Action:      introspectFunc,
			Aliases:     []string{"i"},
		},
		{
			Action:      loginFunc,
			Description: "Retrieve logins",
			Name:        "logins",
			Aliases:     []string{"l"},
			Flags:       []cli.Flag{},
		},
		{
			Action:      itemUsageFunc,
			Name:        "item-usage-report",
			Description: "Retrieve item usages",
			Aliases:     []string{"iur"},
		},
	}
	if err := app.Run(os.Args); err != nil {
		log.Fatal(err)
	}
}
